global:
  scrape_interval: 15s # Scan data moi 15s

scrape_configs:
  - job_name: "pigbox-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9090"]
    metrics_path: "/metrics"

  - job_name: "pigbox-app"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9194" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "pigbox-node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9100" ]

  - job_name: "pigbox-mysql-node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9104" ]
    metrics_path: "/metrics"
